# Generated by Django 2.0.7 on 2018-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='img/dp/placeholder2.png', upload_to='img/'),
        ),
    ]
