# Generated by Django 2.0.7 on 2018-07-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='color',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
