# Generated by Django 2.0.7 on 2018-07-29 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20180729_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('GREEN', 'Green'), ('RED', 'Red'), ('PURPLE', 'Purple'), ('YELLOW', 'Yellow')], default='BLUE', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='dp/placeholder2.png', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
